<?php
// This file is dynamically generated by logos-settings.php
// Do not edit this file directly.

define('APP_LOGO_PATH', '/uploads/assets/APP_LOGO_PATH_686ccc13d39b57.32819583.jpg');
define('APP_FAVICON_PATH', '/uploads/assets/APP_FAVICON_PATH_686ccc13d3de54.57522360.jpg');
define('OG_IMAGE_PATH', '/uploads/assets/OG_IMAGE_PATH_6869a26510b0d7.90344648.png');
define('APP_CROPPED_LOGO_PATH', '/uploads/assets/APP_CROPPED_LOGO_PATH_6869a26510fdc0.76014210.jpg');
