<?php
// This file is dynamically generated by website-settings.php
// Do not edit this file directly.

define('APP_TITLE', 'Dinak din tha');
define('APP_SITE_URL', 'https://etest.netigadarnews.in');
define('APP_ADMIN_EMAIL', 'takadimthom@gma.com');
define('APP_EDITOR_NAME', 'tesln');
define('APP_MD_CHAIRMEN_NAME', 'takadimthom@gma.com');
define('APP_EMAIL', 'takadimthom@gma.com');
define('APP_PHONE', '+91923989xxxx');
define('APP_ADDRESS', 'H. No. 11-857/B
Subhash Nagar Colony, Madanapalli,
Chittor, AP, 500010');
