<?php
// This file is dynamically generated by social-media-settings.php
// Do not edit this file directly.

define('APP_FACEBOOK_URL', 'https://www.123.coms');
define('APP_TWITTER_URL', 'https://twitter.com');
define('APP_INSTAGRAM_URL', 'https://www.123.com');
define('APP_WHATSAPP_URL', 'https://www.123.com');
define('APP_YOUTUBE_URL', 'https://www.123.com');
